# Generated by Django 4.1.13 on 2024-04-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gb_app5', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.0, max_digits=2),
        ),
    ]
